server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:reportdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.springframework: INFO
